### ISSUE TITLE
Change prop "icon" to "name"

### ISSUE THREAD

**Issue by KyleAMathews** [KyleAMathews/react-icon-factory#2]
Just alias for now to avoid having to bump the major version.

**Comment by ckknight** [comment]
:+1:

`<Icon icon="blah" />` is awkward.

**Comment by KyleAMathews** [comment]
Yeah, didn't think that through very clearly obviously :-)

**Comment by KyleAMathews** [comment]
And just released a 2.0 cause versions are cheap.
